### ISSUE TITLE
[Intern4] Add new libraries

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12269]
- [x] jquery-localize -- https://github.com/cdnjs/cdnjs/issues/9563
- [x] angular-css-injector -- https://github.com/cdnjs/cdnjs/issues/7598
- [x] selectonic -- https://github.com/cdnjs/cdnjs/issues/8129
- [ ] chris-rudmin/Recorderjs -- https://github.com/cdnjs/cdnjs/issues/8685
- [ ] wysiwyg.css -- https://github.com/cdnjs/cdnjs/issues/9117
- [x] exceljs -- https://github.com/cdnjs/cdnjs/issues/9463
- [ ] ng2-restangular -- https://github.com/2muchcoffeecom/ng2-restangular
- [ ] map-icons -- https://github.com/cdnjs/cdnjs/issues/9539
- [x] jqueryrotate -- https://github.com/cdnjs/cdnjs/issues/10271
- [x] multi.js -- https://github.com/cdnjs/cdnjs/issues/10550
- [ ] datatable -- https://github.com/cdnjs/cdnjs/issues/10718
- [x] Redux-Search -- https://github.com/cdnjs/cdnjs/issues/10697
 - [ ] Web-Ticker -- https://github.com/cdnjs/cdnjs/issues/10629
- [ ] js-xlsx -- https://github.com/cdnjs/cdnjs/issues/10615
- [ ] DragDrop -- https://github.com/cdnjs/cdnjs/issues/10604
- [ ]  [mag.js](https://github.com/magnumjs/mag.js) -- cdnjs/cdnjs#10603
- [x]  [xStore](https://github.com/florian/xStore) -- cdnjs/cdnjs#10602
- [x]  [rssi](https://github.com/mvasilkov/rssi) -- cdnjs/cdnjs#10601
- [x] css-toggle-switch https://github.com/cdnjs/cdnjs/issues/11549 (git)
- [x] country-select-js https://github.com/cdnjs/cdnjs/issues/11462 (git)
- [x] jSignature https://github.com/cdnjs/cdnjs/issues/11455 (git)
- [x] Rison https://github.com/cdnjs/cdnjs/issues/11505 (npm)
- [x] videojs-flash.js https://github.com/cdnjs/cdnjs/issues/11517 (npm)
- [x] jquery.localize.js https://github.com/cdnjs/cdnjs/issues/9563 (npm)

cc cdnjs/cdnjs#10165 cdnjs/cdnjs#9414

**Comment by ralphchung** [comment]
I wanna take country-select-js.

**Comment by cy91244** [comment]
I will take  videojs-flash.js

**Comment by jeremywu3** [comment]
i wanna take jquery.localize.js

**Comment by AilurusUmbra** [comment]
I will take datatable -- #10718

**Comment by finch185277** [comment]
i want to take  jquery.localize.js #12251 (npm)

**Comment by finch185277** [comment]
[change] i take Rison #11505 (npm)

**Comment by AilurusUmbra** [comment]
I take  selectonic -- #8129

**Comment by cy91244** [comment]
I will take Redux-Search

**Comment by finch185277** [comment]
i want take Web-Ticker

**Comment by cy91244** [comment]
I will take js-xlsx -- #10615

**Comment by finch185277** [comment]
I will take DragDrop -- #10604

**Comment by finch185277** [comment]
I will take map-icons -- #9539

**Comment by MattIPv4** [comment]
We no longer have interns working on cdnjs, closing.
