### ISSUE TITLE
PR and request issue review checklist

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5315]
We need a checklist for maintainer to confirm if a **PR** or **lib adding request issue** should be accept.

Here is the checklist I thought of currently:
- [ ] Not found on cdnjs repo
- [ ] No already exist issue and PR
- [ ] Notable popularity
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
- [ ] Has valid tags for each versions (for git auto-update)
- [ ] Auto-update setup
- [ ] Auto-update target/source is valid.
- [ ] Auto-update filemap is correct.

**Comment by PeterDaveHello** [comment]
Tag @cdnjs/team-cdnjs @cdnjs/intern for comments.

**Comment by IonicaBizau** [comment]
How do we define *Notable popularity*?

**Comment by PeterDaveHello** [comment]
> How do we define Notable popularity?
Currently, about 100 stars on GitHub, but not a clearly defined yet.

**Comment by maruilian11** [comment]
if they don't match the request, do we need to close them?

**Comment by PeterDaveHello** [comment]
It depends on the reporter, if there is no response, yes, we close it.

**Comment by drewfreyling** [comment]
@PeterDaveHello I think the the "100 starts but leave it to our discretion" is fine.

**Comment by drewfreyling** [comment]
What about a link to where the user got the files from? Or do you consider that part of " Project has public repository"?

**Comment by drewfreyling** [comment]
Do we need any guidance on what to do if the library is a fork or not the "main" repo people would expect?

**Comment by PeterDaveHello** [comment]
@drewfreyling :
"100 starts but leave it to our discretion" is fine for me too.
I think we need "the link to where the user got the files from" when auto-update not configured.

The guide of the forked or non-main repo may be needed, but hard to document that, maybe you can open an issue ticket and share your idea with us?

**Comment by Amomo** [comment]
got it ! :+1:

**Comment by PeterDaveHello** [comment]
@cdnjs/team-cdnjs @cdnjs/intern 

We have been using this workflow for a while and seems it really helps, let's make this checklist confirmed, and then add it to the document.

I need you to help me check all the check points in the checklist above and give me some feedback about maybe there need to be one more check or something, thanks!

**Comment by LeaYeh** [comment]
I think this form of the checklist is good now.
